extends Node


## HEY THERE, THIS IS WHERE I'M THINKING OF PUTTING IDEAS AND THINKS WE NEED TO DO.

## 1. WE NEED MORE TAGS, I WOULD MAKE MORE BUT I'M TIRED AND HAVE NO CREATIVITY YOU MAKE THE TAGS AND I PUT THEM HERE LATER
